### ISSUE TITLE
Units for fracture toughness values in PFM `json` input files

### ISSUE THREAD

**Issue by Gfacco** [NRC-Research/FAVPRO_REFOUT#15]
## Description
Currently the in the PFM `json` input files the value `"max K"` is unitless
## Desired Behavior 
`"max K"` should be in units of `"ksi in^0.5"` of other acceptable units

**Comment by kmorris-si** [comment]
@praynaud The bugs reported need to change in the  corresponding input json files in directory FAVPRO_REFOUT/FAVPFMin/

**Comment by praynaud** [comment]
@kmorris-si @Gfacco I had done this but it got overwritten when the branch was updated with `main` after the last PR was merged. I believe I have fixed it again.

**Comment by kmorris-si** [comment]
@praynaud Thank you sorry for the duplicate work
