### ISSUE TITLE
PFM input `json` files not matching `*.in` files 

### ISSUE THREAD

**Issue by Gfacco** [NRC-Research/FAVPRO_REFOUT#16]
For  three of the PFM verification tests the `json` files do not match the `*.in` files

- [x] pfm_test_ver_22 
- [x] pfm_test_ver_23 
- [x] pfm_test_ver_24

**Comment by praynaud** [comment]
@Gfacco Could you be a little more specific so that I can make the fix? I suspect this will also mean updating the AIG.

**Comment by Gfacco** [comment]
The `json` files are "deterministic history" input files but it the `*.in` files are `IQA = 2 "CRITICAL RTNDT ANALYSIS"`

**Comment by praynaud** [comment]
@Gfacco thanks, I will try and fix by Friday... it's appraisal time, so I have to waste hours doing that between now and then...

**Comment by praynaud** [comment]
@Gfacco This is now fixed, as well as some bugs in the AIG that caused this behavior.  Commit: https://github.com/NRC-Research/FAVPRO_REFOUT/commit/533f63f38795a22ce564717d026f545ef02426c3
