### ISSUE TITLE
PFM json input files field related to time needs units

### ISSUE THREAD

**Issue by kmorris-si** [NRC-Research/FAVPRO_REFOUT#2]
# Summary

The json file input for pfm  has the following json element:
```    
"analysis time interval specification" : [
      {
        "pfm transient number" : 1,
        "thermal-hydraulic sequence number" : 2,
        "start time" : 0.0,
        "end time" : 300.0
      },
```

# Expected Behavior

The "start time" and "end time" fields should have the appropriate units

# Actual Behavior

The "start time" and "end time" fields have no units

# Relevant inputs and/or outputs

N/A

# Possible fixes

The json file should look as below
```
"analysis time interval specification" : [
      {
        "pfm transient number" : 1,
        "thermal-hydraulic sequence number" : 2,
        "start time" : "0.0 m",
        "end time" : "300.0 m"
      },

**Comment by praynaud** [comment]
@kmorris-si I have a PR ready to fix this.  Please take a look and merge if you agree.  Also, there is an invitation pending for you for this repo. Please accept it. Thanks!
