### ISSUE TITLE
  `json` files for `favPFM` missing `wps_option` for `"deterministic critical RTndt"` 

### ISSUE THREAD

**Issue by Gfacco** [NRC-Research/FAVPRO_REFOUT#28]
## Decription
 The `json` files for `favPFM` critical RTNDT analysis are missing an input for the weld prestress variable `WPS_OPTION`
which can be 0, 1, or 2.

## Current input file

```
{
  "deterministic critical RTndt" : {
    "weld residual stress" : false,
    "percentile" : 0.0
  }
}
```

## Suggested input file

```
{
  "deterministic critical RTndt" : {
    "weld residual stress" : false,
    "percentile" : 0.0, 
    "weld prestress" : 1
  }
}
```

## Files affected

         pfm_test_ver_22 
         pfm_test_ver_23 
         pfm_test_ver_24

**Comment by praynaud** [comment]
@Gfacco I will take care of this right now. Can you please first merge PR #27 which fixes you other issue?

**Comment by Gfacco** [comment]
@praynaud done, thanks!
