### ISSUE TITLE
Syntax Error in FAVLOAD Input Files

### ISSUE THREAD

**Issue by everythingfunctional** [NRC-Research/FAVPRO_REFOUT#4]
It appears there is a syntax error in the FAVLOAD JSON input files. The symbol to close the list of transients is a `}` but should be a `]`. For example, line 435 of `load/val_1.json` is `}` but should be `]`.

**Comment by praynaud** [comment]
@everythingfunctional Thanks for reporting. I should have a PR to fix this before tomorrow AM.

**Comment by praynaud** [comment]
@everythingfunctional Done and merged. I ran all the files through [jsonlint](https://jsonlint.com/)
